typography_spectrum: 0.48705
color:
  brandColors:
    - '#6064c3'
    - '#454bba'
    - '#282c73'
    - '#16183e'
    - '#8387d0'
  brandStrength: 1
  lightness: 0.1875
  saturation: 0
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0
analytics:
  google: null
  facebook: null
  twitter: null
name: ionlawrence.com
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Use what You can
purpose: []
