name: ionlawrence.com
favicon: null
layout_spectrum: 1
typography_spectrum: 0.48705
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6064c3'
    - '#454bba'
    - '#282c73'
    - '#16183e'
    - '#8387d0'
  brandStrength: 1
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0
purpose: []
